# Maven
target/
!target/*.jar
mvnw*
.mvn

# Git
.git
.gitignore

# IDE
.idea/
*.iml
.vscode/
.settings/
.project
.classpath

# Logs
*.log

# Environment files
.env*

# Docker
Dockerfile
docker-compose*.yml

# Misc
README.md
*.md