-- ========================================
-- NHX Server Database Schema - Initial Setup
-- ========================================

-- Create users table
CREATE TABLE users (
                       user_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       username VARCHAR(255) NOT NULL,
                       email VARCHAR(255) NOT NULL,
                       phone_number VARCHAR(255) NOT NULL,
                       password VARCHAR(255) NOT NULL,
                       first_name VARCHAR(255),
                       last_name VARCHAR(255),
                       kyc_status VARCHAR(50) DEFAULT 'PENDING',
                       kyc_reference VARCHAR(255),
                       account_non_expired BOOLEAN DEFAULT TRUE NOT NULL,
                       account_non_locked BOOLEAN DEFAULT TRUE NOT NULL,
                       credentials_non_expired BOOLEAN DEFAULT TRUE NOT NULL,
                       enabled BOOLEAN DEFAULT FALSE NOT NULL,
                       email_verified BOOLEAN DEFAULT FALSE NOT NULL,
                       profile_image_url VARCHAR(500),
                       wallet_address VARCHAR(255),
                       created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
                       updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL
);

-- Create roles table
CREATE TABLE roles (
                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       name VARCHAR(20) NOT NULL
);

-- Create user_roles junction table
CREATE TABLE user_roles (
                            user_id BIGINT NOT NULL,
                            role_id BIGINT NOT NULL,
                            CONSTRAINT pk_user_roles PRIMARY KEY (user_id, role_id)
);

-- Create refresh_tokens table
CREATE TABLE refresh_tokens (
                                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                user_id BIGINT NOT NULL,
                                token VARCHAR(500) NOT NULL,
                                expiry_date TIMESTAMP WITHOUT TIME ZONE NOT NULL
);

-- Create password_reset_tokens table
CREATE TABLE password_reset_tokens (
                                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                       token VARCHAR(500) NOT NULL,
                                       user_id BIGINT NOT NULL,
                                       expiry_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
                                       used BOOLEAN DEFAULT FALSE NOT NULL
);

-- Create email_verification_tokens table
CREATE TABLE email_verification_tokens (
                                           id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                           token VARCHAR(500) NOT NULL,
                                           user_id BIGINT NOT NULL,
                                           expiry_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
                                           created_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
                                           verified_date TIMESTAMP WITHOUT TIME ZONE,
                                           used BOOLEAN DEFAULT FALSE NOT NULL
);

-- Create assets table
CREATE TABLE asset (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    asset_type VARCHAR(255),
    name VARCHAR(255) NOT NULL,
    asset_ticker VARCHAR(255),
    date_updated TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE
);

-- Create portfolio_snapshots table
CREATE TABLE portfolio_snapshots (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    date DATE NOT NULL,
    balance DECIMAL(19, 8) NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE
);

-- ========================================
-- Add Unique Constraints
-- ========================================

ALTER TABLE users
    ADD CONSTRAINT uc_users_username UNIQUE (username);

ALTER TABLE users
    ADD CONSTRAINT uc_users_email UNIQUE (email);

ALTER TABLE users
    ADD CONSTRAINT uc_users_phone_number UNIQUE (phone_number);

ALTER TABLE roles
    ADD CONSTRAINT uc_roles_name UNIQUE (name);

ALTER TABLE refresh_tokens
    ADD CONSTRAINT uc_refresh_tokens_token UNIQUE (token);

ALTER TABLE refresh_tokens
    ADD CONSTRAINT uc_refresh_tokens_user UNIQUE (user_id);

ALTER TABLE password_reset_tokens
    ADD CONSTRAINT uc_password_reset_tokens_token UNIQUE (token);

ALTER TABLE password_reset_tokens
    ADD CONSTRAINT uc_password_reset_tokens_user UNIQUE (user_id);

ALTER TABLE email_verification_tokens
    ADD CONSTRAINT uc_email_verification_tokens_token UNIQUE (token);

ALTER TABLE email_verification_tokens
    ADD CONSTRAINT uc_email_verification_tokens_user UNIQUE (user_id);

-- ========================================
-- Add Foreign Key Constraints
-- ========================================

ALTER TABLE user_roles
    ADD CONSTRAINT fk_user_roles_user FOREIGN KEY (user_id)
        REFERENCES users(user_id) ON DELETE CASCADE;

ALTER TABLE user_roles
    ADD CONSTRAINT fk_user_roles_role FOREIGN KEY (role_id)
        REFERENCES roles(id) ON DELETE CASCADE;

ALTER TABLE refresh_tokens
    ADD CONSTRAINT fk_refresh_tokens_user FOREIGN KEY (user_id)
        REFERENCES users(user_id) ON DELETE CASCADE;

ALTER TABLE password_reset_tokens
    ADD CONSTRAINT fk_password_reset_tokens_user FOREIGN KEY (user_id)
        REFERENCES users(user_id) ON DELETE CASCADE;

ALTER TABLE email_verification_tokens
    ADD CONSTRAINT fk_verify_user FOREIGN KEY (user_id)
        REFERENCES users(user_id) ON DELETE CASCADE;

-- ========================================
-- Create Indexes for Performance
-- ========================================

-- User lookup indexes
CREATE INDEX idx_users_email ON users(email);
CREATE INDEX idx_users_username ON users(username);
CREATE INDEX idx_users_phone_number ON users(phone_number);
CREATE INDEX idx_users_wallet_address ON users(wallet_address);

-- Token lookup indexes
CREATE INDEX idx_refresh_tokens_token ON refresh_tokens(token);
CREATE INDEX idx_refresh_tokens_expiry ON refresh_tokens(expiry_date);

CREATE INDEX idx_password_reset_tokens_token ON password_reset_tokens(token);
CREATE INDEX idx_password_reset_tokens_expiry ON password_reset_tokens(expiry_date);

CREATE INDEX idx_email_verification_tokens_token ON email_verification_tokens(token);
CREATE INDEX idx_email_verification_tokens_user_id ON email_verification_tokens(user_id);
CREATE INDEX idx_email_verification_tokens_expiry ON email_verification_tokens(expiry_date);

-- User roles lookup index
CREATE INDEX idx_user_roles_user_id ON user_roles(user_id);
CREATE INDEX idx_user_roles_role_id ON user_roles(role_id);

-- ========================================
-- Comments for Documentation
-- ========================================

COMMENT ON TABLE users IS 'Stores user account information';
COMMENT ON TABLE roles IS 'Stores system roles (ROLE_USER, ROLE_MODERATOR, ROLE_ADMIN)';
COMMENT ON TABLE user_roles IS 'Many-to-many relationship between users and roles';
COMMENT ON TABLE refresh_tokens IS 'Stores JWT refresh tokens for authentication';
COMMENT ON TABLE password_reset_tokens IS 'Stores tokens for password reset functionality';
COMMENT ON TABLE email_verification_tokens IS 'Stores tokens for email verification';

COMMENT ON COLUMN users.kyc_status IS 'KYC verification status: PENDING, IN_PROGRESS, APPROVED, REJECTED, EXPIRED';
COMMENT ON COLUMN users.wallet_address IS 'Hedera blockchain wallet address';