-- ========================================
-- NHX Server Database Schema
-- ========================================

-- Create users table
CREATE TABLE users (
                       user_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       username VARCHAR(255),
                       email VARCHAR(255) NOT NULL,
                       phone_number VARCHAR(255),
                       password VARCHAR(255) NOT NULL,
                       full_name VARCHAR(255),
                       enabled BOOLEAN DEFAULT FALSE NOT NULL,
                       email_verified BOOLEAN DEFAULT FALSE NOT NULL,
                       profile_image_url VARCHAR(500),
                       wallet_address VARCHAR(255),
                       created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
                       updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL
);

-- Create roles table
CREATE TABLE roles (
                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       name VARCHAR(20) NOT NULL
);

-- Create user_roles junction table
CREATE TABLE user_roles (
                            user_id BIGINT NOT NULL,
                            role_id BIGINT NOT NULL,
                            CONSTRAINT pk_user_roles PRIMARY KEY (user_id, role_id)
);

-- Create refresh_tokens table
CREATE TABLE refresh_tokens (
                                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                user_id BIGINT NOT NULL,
                                token VARCHAR(500) NOT NULL,
                                expiry_date TIMESTAMP WITHOUT TIME ZONE NOT NULL
);

-- Create password_reset_tokens table
CREATE TABLE password_reset_tokens (
                                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                       token VARCHAR(500) NOT NULL,
                                       user_id BIGINT NOT NULL,
                                       expiry_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
                                       used BOOLEAN DEFAULT FALSE NOT NULL
);

-- Create email_verification_tokens table
CREATE TABLE email_verification_tokens (
                                           id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                           token VARCHAR(500) NOT NULL,
                                           user_id BIGINT NOT NULL,
                                           expiry_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
                                           created_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
                                           verified_date TIMESTAMP WITHOUT TIME ZONE,
                                           used BOOLEAN DEFAULT FALSE NOT NULL
);

-- Create asset table
CREATE TABLE asset (
                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       user_id BIGINT NOT NULL,
                       asset_type VARCHAR(255),
                       name VARCHAR(255),
                       asset_ticker VARCHAR(255),
                       date_updated TIMESTAMP WITHOUT TIME ZONE
);

-- Create payment_method table
CREATE TABLE payment_method (
                                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                user_id BIGINT NOT NULL,
                                name VARCHAR(255),
                                mobile_number VARCHAR(255),
                                date_added TIMESTAMP WITHOUT TIME ZONE
);

-- Create payment_transaction table
CREATE TABLE payment_transaction (
                                     id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                     transaction_id VARCHAR(255),
                                     user_id BIGINT NOT NULL,
                                     type VARCHAR(50),
                                     method VARCHAR(255),
                                     amount DECIMAL(19, 2),
                                     currency VARCHAR(10),
                                     status VARCHAR(50),
                                     date TIMESTAMP WITHOUT TIME ZONE,
                                     description TEXT
);

-- Create portfolio_snapshot table
CREATE TABLE portfolio_snapshot (
                                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                    user_id BIGINT NOT NULL,
                                    date DATE,
                                    balance DECIMAL(19, 8),
                                    created_at TIMESTAMP WITHOUT TIME ZONE
);

-- Create product_access table
CREATE TABLE product_access (
                                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                user_id BIGINT NOT NULL,
                                name VARCHAR(255),
                                description TEXT,
                                access BOOLEAN,
                                minimum_deposit DECIMAL(19, 2),
                                fees DECIMAL(19, 2),
                                custodian VARCHAR(255)
);

-- Create transaction table
CREATE TABLE transaction (
                             id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                             transaction_id VARCHAR(255),
                             user_id BIGINT NOT NULL,
                             stock VARCHAR(255),
                             amount DECIMAL(19, 2),
                             quantity DECIMAL(19, 8),
                             type VARCHAR(50),
                             date TIMESTAMP WITHOUT TIME ZONE
);

-- ========================================
-- Add Unique Constraints
-- ========================================

ALTER TABLE users
    ADD CONSTRAINT uc_users_username UNIQUE (username);

ALTER TABLE users
    ADD CONSTRAINT uc_users_email UNIQUE (email);

ALTER TABLE users
    ADD CONSTRAINT uc_users_phone_number UNIQUE (phone_number);

ALTER TABLE roles
    ADD CONSTRAINT uc_roles_name UNIQUE (name);

ALTER TABLE refresh_tokens
    ADD CONSTRAINT uc_refresh_tokens_token UNIQUE (token);

ALTER TABLE refresh_tokens
    ADD CONSTRAINT uc_refresh_tokens_user UNIQUE (user_id);

ALTER TABLE password_reset_tokens
    ADD CONSTRAINT uc_password_reset_tokens_token UNIQUE (token);

ALTER TABLE password_reset_tokens
    ADD CONSTRAINT uc_password_reset_tokens_user UNIQUE (user_id);

ALTER TABLE email_verification_tokens
    ADD CONSTRAINT uc_email_verification_tokens_token UNIQUE (token);

ALTER TABLE email_verification_tokens
    ADD CONSTRAINT uc_email_verification_tokens_user UNIQUE (user_id);

-- ========================================
-- Add Foreign Key Constraints
-- ========================================

ALTER TABLE user_roles
    ADD CONSTRAINT fk_user_roles_user FOREIGN KEY (user_id)
        REFERENCES users(user_id) ON DELETE CASCADE;

ALTER TABLE user_roles
    ADD CONSTRAINT fk_user_roles_role FOREIGN KEY (role_id)
        REFERENCES roles(id) ON DELETE CASCADE;

ALTER TABLE refresh_tokens
    ADD CONSTRAINT fk_refresh_tokens_user FOREIGN KEY (user_id)
        REFERENCES users(user_id) ON DELETE CASCADE;

ALTER TABLE password_reset_tokens
    ADD CONSTRAINT fk_password_reset_tokens_user FOREIGN KEY (user_id)
        REFERENCES users(user_id) ON DELETE CASCADE;

ALTER TABLE email_verification_tokens
    ADD CONSTRAINT fk_email_verification_tokens_user FOREIGN KEY (user_id)
        REFERENCES users(user_id) ON DELETE CASCADE;

ALTER TABLE asset
    ADD CONSTRAINT fk_asset_user FOREIGN KEY (user_id)
        REFERENCES users(user_id) ON DELETE CASCADE;

ALTER TABLE payment_method
    ADD CONSTRAINT fk_payment_method_user FOREIGN KEY (user_id)
        REFERENCES users(user_id) ON DELETE CASCADE;

ALTER TABLE payment_transaction
    ADD CONSTRAINT fk_payment_transaction_user FOREIGN KEY (user_id)
        REFERENCES users(user_id) ON DELETE CASCADE;

ALTER TABLE portfolio_snapshot
    ADD CONSTRAINT fk_portfolio_snapshot_user FOREIGN KEY (user_id)
        REFERENCES users(user_id) ON DELETE CASCADE;

ALTER TABLE product_access
    ADD CONSTRAINT fk_product_access_user FOREIGN KEY (user_id)
        REFERENCES users(user_id) ON DELETE CASCADE;

ALTER TABLE transaction
    ADD CONSTRAINT fk_transaction_user FOREIGN KEY (user_id)
        REFERENCES users(user_id) ON DELETE CASCADE;

-- ========================================
-- Create Indexes for Performance
-- ========================================

-- User lookup indexes
CREATE INDEX idx_users_email ON users(email);
CREATE INDEX idx_users_username ON users(username);
CREATE INDEX idx_users_phone_number ON users(phone_number);
CREATE INDEX idx_users_wallet_address ON users(wallet_address);

-- Token lookup indexes
CREATE INDEX idx_refresh_tokens_token ON refresh_tokens(token);
CREATE INDEX idx_refresh_tokens_expiry ON refresh_tokens(expiry_date);

CREATE INDEX idx_password_reset_tokens_token ON password_reset_tokens(token);
CREATE INDEX idx_password_reset_tokens_expiry ON password_reset_tokens(expiry_date);

CREATE INDEX idx_email_verification_tokens_token ON email_verification_tokens(token);
CREATE INDEX idx_email_verification_tokens_user_id ON email_verification_tokens(user_id);
CREATE INDEX idx_email_verification_tokens_expiry ON email_verification_tokens(expiry_date);

-- User roles lookup index
CREATE INDEX idx_user_roles_user_id ON user_roles(user_id);
CREATE INDEX idx_user_roles_role_id ON user_roles(role_id);

-- Asset indexes
CREATE INDEX idx_asset_user_id ON asset(user_id);
CREATE INDEX idx_asset_ticker ON asset(asset_ticker);

-- Payment method indexes
CREATE INDEX idx_payment_method_user_id ON payment_method(user_id);

-- Payment transaction indexes
CREATE INDEX idx_payment_transaction_user_id ON payment_transaction(user_id);
CREATE INDEX idx_payment_transaction_id ON payment_transaction(transaction_id);
CREATE INDEX idx_payment_transaction_status ON payment_transaction(status);
CREATE INDEX idx_payment_transaction_date ON payment_transaction(date);

-- Portfolio snapshot indexes
CREATE INDEX idx_portfolio_snapshot_user_id ON portfolio_snapshot(user_id);
CREATE INDEX idx_portfolio_snapshot_date ON portfolio_snapshot(date);
CREATE INDEX idx_portfolio_snapshot_user_date ON portfolio_snapshot(user_id, date);

-- Product access indexes
CREATE INDEX idx_product_access_user_id ON product_access(user_id);

-- Transaction indexes
CREATE INDEX idx_transaction_user_id ON transaction(user_id);
CREATE INDEX idx_transaction_id ON transaction(transaction_id);
CREATE INDEX idx_transaction_date ON transaction(date);
CREATE INDEX idx_transaction_stock ON transaction(stock);

-- ========================================
-- Comments for Documentation
-- ========================================

COMMENT ON TABLE users IS 'Stores user account information';
COMMENT ON TABLE roles IS 'Stores system roles (ROLE_USER, ROLE_MODERATOR, ROLE_ADMIN)';
COMMENT ON TABLE user_roles IS 'Many-to-many relationship between users and roles';
COMMENT ON TABLE refresh_tokens IS 'Stores JWT refresh tokens for authentication';
COMMENT ON TABLE password_reset_tokens IS 'Stores tokens for password reset functionality';
COMMENT ON TABLE email_verification_tokens IS 'Stores tokens for email verification';
COMMENT ON TABLE asset IS 'Stores user assets/investments';
COMMENT ON TABLE payment_method IS 'Stores user payment methods (e.g., Mpesa)';
COMMENT ON TABLE payment_transaction IS 'Stores deposit and withdrawal transactions';
COMMENT ON TABLE portfolio_snapshot IS 'Stores daily portfolio balance snapshots';
COMMENT ON TABLE product_access IS 'Stores user access to investment products';
COMMENT ON TABLE transaction IS 'Stores buy/sell stock transactions';

COMMENT ON COLUMN users.wallet_address IS 'Blockchain wallet address';
COMMENT ON COLUMN payment_transaction.type IS 'Transaction type: deposit or withdrawal';
COMMENT ON COLUMN payment_transaction.status IS 'Transaction status: pending, completed, failed';
COMMENT ON COLUMN transaction.type IS 'Transaction type: buy or sell';